### PR TITLE
Added equivalences

### PR DESCRIPTION
**Pull request by nmvdw**
I added the definition of equivalences. We need this to make adjoint equivalences. Equivalences can be refined to adjoint equivalences (next step).

### CODE REVIEW

**Comment by benediktahrens** [comment]
Also, I think that the adjointification is already in B&M

**Comment by nmvdw** [comment]
> If I am not mistaken, there are already equivalences and adjoint equivalences in the B&M library. You should make your definitions aliases for the existing ones in UniMath?

The equivalences I added, are _not_ adjoint equivalences. No triangles equations are satisfied. I need it for refining equivalences to adjoint equivalences.

>Also, I think that the adjointification is already in B&M

I couldn't find it.

**Comment by co-dan** [comment]
Related: an issue about adjoint equivalences: https://github.com/benediktahrens/bicats/issues/16

**Comment by benediktahrens** [comment]
On 19/11/2018 16:33, Niels van der Weide wrote:
>     If I am not mistaken, there are already equivalences and adjoint
>     equivalences in the B&M library. You should make your definitions
>     aliases for the existing ones in UniMath?
> 
> The equivalences I added, are /not/ adjoint equivalences. No triangles 
> equations are satisfied. I need it for refining equivalences to adjoint 
> equivalences.
> 
>     Also, I think that the adjointification is already in B&M
> 
> I couldn't find it.

Sorry, that just existed in my head :-) I had started doing that, but 
then never finished it.

Merged, I am now waiting for the PR to UniMath/UniMath to pass the CI.

**Pull request merged**
