### PR TITLE
Changed internal equivalences

### PR DESCRIPTION
**Pull request by nmvdw**
I added internal equivalences by extending B&M. I also modified the definition of adjoint equivalences (as described in https://github.com/benediktahrens/bicats/issues/16 ).

### CODE REVIEW

**Comment by benediktahrens** [comment]
@nmvdw : This PR has a problem that I don't fully understand - the CI complains that it cannot merge the PR into the branch to test against, but it seems possible without problems to merge the PR. I have no clue...

Anyway, I think it is better if from now on, everybody files PRs against UniMath/UniMath directly. I have done that with this PR, see https://github.com/UniMath/UniMath/pull/1065.

**Comment by co-dan** [comment]
@benediktahrens Sorry, just to make sure that I understand you correctly: if we change something we make a pull request against the main repository? Do we need to notify you then or something?

**Comment by co-dan** [comment]
PS, if you want to work directly at the UniMath repository, maybe it is possible to have a tag for all the stuff related to bicategories?

**Comment by benediktahrens** [comment]
On 20/11/2018 11:36, Dan Frumin wrote:
> @benediktahrens <https://github.com/benediktahrens> Sorry, just to make 
> sure that I understand you correctly: if we change something we make a 
> pull request against the main repository? Do we need to notify you then 
> or something?

Yes, exactly. I have done this again for now:

https://github.com/UniMath/UniMath/pull/1070

But there is no reason for you not to file these PRs yourselves.

I am automatically notified of every PR to UniMath. Dan Grayson and I 
are the ones who merge PRs.

**Comment by benediktahrens** [comment]
Merged into UniMath/UniMath, closing this PR.

**Pull request closed without merging**
