### PR TITLE
Fixing bicategories

### PR DESCRIPTION
**Pull request by nmvdw**
- The definition `is_pregroupoid` is about categories. We use precategories in Univalence.v (in bicategories) and there categories can't be used.  Do we want this definition for precategories or categories?
- By removing the infrastructure related to precategories, the part on WkCatEnrichment (an equivalent definition) needs more involved rewriting, so that set assumptions are more frequently used. What do we want to do with that part? This is also the reason why it got stuck on `Bicat.v`, because there some of the relevant transformations are defined.

### CODE REVIEW

**Comment by benediktahrens** [comment]
>     * The definition `is_pregroupoid` is about categories. We use precategories in Univalence.v (in bicategories) and there categories can't be used.  Do we want this definition for precategories or categories?
> 
>     * By removing the infrastructure related to precategories, the part on WkCatEnrichment (an equivalent definition) needs more involved rewriting, so that set assumptions are more frequently used. What do we want to do with that part? This is also the reason why it got stuck on `Bicat.v`, because there some of the relevant transformations are defined.

Thanks a lot. I need to take some time to understand the first point you are raising - will look into it after my meeting right now.

**Comment by benediktahrens** [comment]
@nmvdw : I took a look at `Bicategories/Core/Univalence.v`, and the file compiles fine. I think I am not understanding your comment. Could you give me a pointer to a definition/result that is problematic? Or should we briefly meet?

**Comment by nmvdw** [comment]
It compiles, because I commented out this part: https://github.com/benediktahrens/UniMath/blob/refactor-univalent-cats/UniMath/Bicategories/Core/Univalence.v#L589

If that parts get uncommented, then it won't compile anymore because `is_pregroupoid` is only defined for categories.

**Comment by benediktahrens** [comment]
> It compiles, because I commented out this part: https://github.com/benediktahrens/UniMath/blob/refactor-univalent-cats/UniMath/Bicategories/Core/Univalence.v#L589
> 
> If that parts get uncommented, then it won't compile anymore because `is_pregroupoid` is only defined for categories.

Thanks a lot! Is this commented-out stuff used elsewhere?

(It is expected that we will have to remove some stuff that does not make sense any more - for instance, the stuff on (co)limits in the precategory of types.)

**Comment by nmvdw** [comment]
It is not used elsewhere.

**Comment by benediktahrens** [comment]
> It is not used elsewhere.

Ok, great. I suggest to leave the file as is, then - people might appreciate the observation, even if there is no suitable definition in UniMath to capture it.

**Pull request merged**
